# Site settings
title: cinematik

description: >- # this means to ignore newlines until "baseurl:"
  Cinematik.app
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.cinematik.app" # the base hostname & protocol for your site, e.g. http://example.com

# User settings
# username: Lorem Ipsum
# user_description: Anon Developer at Lorem Ipsum Dolor
# user_title: Anon Developer
email: info@cinematik.app
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum
# disqus_username: lorem_ipsum

# Build settings
#markdown: kramdown
#highlighter: rouge
#permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
#links:
#  - title: Home
#    url: /
#  - title: Series
#    url: /series
#  - title: Tags
#    url: /tags
#  - title: About Me
#    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
